mytuple=(1,2,3,4)
print(type(mytuple))
print(mytuple)
one_elment_tuple=(1,)
one_elment_tuple1=(1)
print(type(one_elment_tuple))
print(type(one_elment_tuple1))
mylist=[1,2,3,4]
print(type(mylist))
mylist1=tuple([1,2,3,4])
print(type(mylist1))
mytuple3=('idlli','dosa','sambar')
print(mytuple3[2])
#mytuple3.insert(chutney)
print(mytuple3)
print(type(mytuple3))
mytuple4=list(mytuple3)
print(mytuple4)
mytuple4.insert(3,'chutney')
print(mytuple4)
mytuple5=tuple(mytuple4)
print(mytuple5)
print(type(mytuple5))


